eureka:
    client:
        serviceUrl:
            defaultZone: http://${eureka.instance.hostname}:8761/eureka/
    instance:
        hostname: localhost
        prefer-ip-address: true
logging:
    level:
        io:
            seata: info
mybatis:
    mapperLocations: classpath:mapper/*.xml
    typeAliasesPackage: com.skyedu.skyedustorage.entity
server:
    port: 8082
spring:
    application:
        name: storage-server
    cloud:
        alibaba:
            seata:
                tx-service-group: fsp_tx_group
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        password: LIming1314520
        url: jdbc:mysql://39.108.143.188/sky
        username: root
